
=== Late Policy

There are weekly or bi-weekly programming assignments as well as written
homeworks (problem sets). You are encouraged to work together, but you should
write up your own solutions (except for group programming assignments). 

Programming assignments will be due on Fridays. You may submit up to one day
late for any reason.  Late assignments will not be accepted and will receive a
zero.

Submitted programming assignments are eligible for resubmission. Thus, you are
encouraged to submit partially complete work. To be eligible for resubmission, 
your submission must compile and have a minimal set of features implemented, as 
specified by the assignment. You may resubmit up to two times, to earn up to
90\% of the credit the first submit and 70\% of the credit for the second
submit.  The resubmission policy is our way of acknowledging the implementation
challenges you will face in this class. But we also want to keep you on track
and so we provide consequences to help you stay accountable. 

Written homeworks (problem sets) are due in class on the day specified. Late
written homeworks will not be accepted. 

Except for circumstances beyond your control, all extensions must be requested
at least 24 hours in advance of the deadline. Extensions will be granted based
on individual circumstances. Time-management related problems are not valid
reasons for extensions.