include::header.adoc[]

:title: Threads I
:Author Initials: ASN
:Date:    2020-08-15
:Revision: 0.1
:ASST: labs-USERNAME

= {title}

Lab exercises for February 20th.

The goals for this assignment are:

* Understanding the pthread library
* Working with ucontext 

:sectnums:

= Matrix Add  **Due Feb 20**

In the files, `matrix.c`, implement a program that uses M threads to add 
two matrices, placing the result in the second. 

[source, subs="quotes"]
----
----

Requirements/Hints:

* Time how long it takes to compute the result when you have 8 versus 1 thread.
* Leverage spatial locality to ensure the best performance, e.g. split the work by rows in each matrix.

= Funny functions **Due Feb 23**

Implement the following programs based on ucontext. 

== Alternate

In the file, `alternate.c`, write a program that alternates between two functions indefinitely.


From another terminal, use the `kill` command to send a signal to the
`alternate` process. In your C file, describe what happens when a signal is
delivered? How do signals affect the execution of a context?

== Alarm

Can you write a program that alternates between two functions at a set interval?

In the file, `alarm.c`, write a program that alternates between two functions at a set interval. 
Use a kernel timer like in the link:sig_alarm.c[sig_alarm] demo from class.

== TID

How do you track the current context? If a function is running in multiple contexts at once,
how do you know which one is which?

In the file, `tid.c`, write a program where multiple contexts run the same function. Add code so that 
each context can keep track of itself.  


